"""Initial schema

Revision ID: f7fb6d28faf0
Revises: 
Create Date: 2026-06-16 01:28:04.511453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fb6d28faf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('fallback_url', sa.Text(), nullable=True))
    op.add_column('streams', sa.Column('hls_updated_at', sa.DateTime(), nullable=True))
    op.drop_column('streams', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_column('streams', 'hls_updated_at')
    op.drop_column('streams', 'fallback_url')
    # ### end Alembic commands ###
